// SPDX-License-Identifier: GPL-2.0-or-later
// bbport: writes the upscaler's color back into the game's scene color, keeping the game's alpha
// (post-processing reads data from it).
#version 450

layout(local_size_x = 8, local_size_y = 8) in;

layout(binding = 0, rgba16f) uniform readonly image2D upscaled;
layout(binding = 1, rgba16f) uniform image2D scene;

void main() {
    const ivec2 pixel = ivec2(gl_GlobalInvocationID.xy);
    if (any(greaterThanEqual(pixel, imageSize(scene)))) {
        return;
    }
    const vec4 original = imageLoad(scene, pixel);
    imageStore(scene, pixel, vec4(imageLoad(upscaled, pixel).rgb, original.a));
}
